#!/usr/bin/env python3
"""Generate CUDA explicit-instantiation translation units from the registry."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

AUTOMATON_RE = re.compile(
    r"APPLY\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([A-Za-z_][A-Za-z0-9_:]*)\s*\)"
)


def parse_automata(registry: Path) -> list[tuple[str, str]]:
    lines = registry.read_text().splitlines()

    for index, line in enumerate(lines):
        if line.startswith("#define CELLATO_AUTOMATA(APPLY)"):
            macro_lines = [line]
            cursor = index
            while macro_lines[-1].rstrip().endswith("\\"):
                cursor += 1
                if cursor >= len(lines):
                    raise RuntimeError("CELLATO_AUTOMATA macro is not terminated")
                macro_lines.append(lines[cursor])
            macro_body = "\n".join(
                part.rstrip().removesuffix("\\") for part in macro_lines
            )
            automata = AUTOMATON_RE.findall(macro_body)
            if not automata:
                raise RuntimeError(
                    "CELLATO_AUTOMATA does not contain any APPLY entries"
                )
            return automata

    raise RuntimeError("CELLATO_AUTOMATA(APPLY) was not found in the registry")


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text() == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def generated_header() -> str:
    return "// Generated by tools/generate_cuda_instantiations.py. Do not edit.\n\n"


def generated_cmake_header() -> str:
    return "# Generated by tools/generate_cuda_instantiations.py. Do not edit.\n\n"


def instantiation_file(
    impl_header: str,
    macro_name: str,
    automata: list[tuple[str, str]],
) -> str:
    lines = [
        generated_header(),
        f'#include "{impl_header}"\n',
        '#include "automata/registry.hpp"\n',
        '#include "cuda_instantiation/template.cuh"\n\n',
    ]
    lines.extend(f"{macro_name}({config_type})\n" for _, config_type in automata)
    return "".join(lines)


def temporal_file(config_type: str) -> str:
    return "".join(
        [
            generated_header(),
            '#include "cellato/traversers/cuda/temporal.cuh"\n',
            '#include "automata/registry.hpp"\n',
            '#include "cuda_instantiation/template.cuh"\n\n',
            f"CELLATO_INSTANTIATE_CUDA_TEMPORAL_SUITES_FOR_AUTOMATON({config_type})\n",
        ]
    )


def cmake_list(name: str, values: list[str]) -> str:
    if not values:
        return f"set({name})\n"

    lines = [f"set({name}\n"]
    lines.extend(f'    "{value}"\n' for value in values)
    lines.append(")\n")
    return "".join(lines)


def cmake_fragment(all_sources: list[str], temporal_sources: list[str]) -> str:
    return "".join(
        [
            generated_cmake_header(),
            cmake_list("CELLATO_GENERATED_CUDA_INSTANTIATION_SRCS", all_sources),
            "\n",
            cmake_list(
                "CELLATO_GENERATED_TEMPORAL_CUDA_INSTANTIATION_SRCS", temporal_sources
            ),
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--registry", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--cmake-fragment", type=Path, required=True)
    args = parser.parse_args()

    automata = parse_automata(args.registry)
    output_dir = args.output_dir

    simple_source = output_dir / "simple_all.cu"
    spatial_blocking_source = output_dir / "spatial_blocking_all.cu"
    temporal_sources = [
        output_dir / f"temporal_{short_name}.cu" for short_name, _ in automata
    ]

    write_if_changed(
        simple_source,
        instantiation_file(
            "cellato/traversers/cuda/simple.cuh",
            "CELLATO_INSTANTIATE_CUDA_SIMPLE_SUITES_FOR_AUTOMATON",
            automata,
        ),
    )
    write_if_changed(
        spatial_blocking_source,
        instantiation_file(
            "cellato/traversers/cuda/spatial_blocking.cuh",
            "CELLATO_INSTANTIATE_CUDA_SPATIAL_BLOCKING_SUITES_FOR_AUTOMATON",
            automata,
        ),
    )

    for (short_name, config_type), temporal_source in zip(automata, temporal_sources):
        _ = short_name
        write_if_changed(temporal_source, temporal_file(config_type))

    all_sources = [simple_source, spatial_blocking_source, *temporal_sources]
    write_if_changed(
        args.cmake_fragment,
        cmake_fragment(
            [source.as_posix() for source in all_sources],
            [source.as_posix() for source in temporal_sources],
        ),
    )


if __name__ == "__main__":
    main()
